"""Veridian's framework-neutral, proof-carrying assurance kernel."""

from ._attestation import (
    Ed25519Signer,
    ReceiptStatementV1,
    Signer,
    StaticKeyProvider,
    VerificationKeyProvider,
    VerifiedEnvelope,
    sign_attestation,
    sign_receipt,
    verify_attestation,
)
from ._canonical import decode_profile_v1, encode_profile_v1, sha256_digest
from ._context import (
    AnchorContext,
    AnchorHead,
    AnchorStore,
    HistoryStatus,
    NonceRegistry,
    NonceStatus,
    ProofVerificationContext,
    ReplayContext,
    ReplayStatus,
    WitnessStatementV1,
    sign_witness,
)
from ._decision import (
    ClauseResultV1,
    ClauseSeverity,
    ClauseStatus,
    DecisionPayloadV1,
    Disposition,
    aggregate_disposition,
)
from ._errors import (
    AssuranceDependencyError,
    AssuranceError,
    AssurancePolicyError,
    AssuranceValidationError,
    AssuranceVerificationError,
)
from ._evidence import EvidenceRef, EvidenceTrust
from ._model import (
    ActionSemanticsV1,
    AuthorizationEnvelope,
    CompletionSemanticsV1,
    TransportBinding,
)
from ._proof import ProofBundleV1, ProofErrorCode, ProofVerification, verify_proof_bundle
from ._snapshot import VerificationSnapshotV1
from ._telemetry import (
    OTEL_SEMCONV_SCHEMA_V1,
    AssuranceTelemetryEventV1,
    AssuranceTelemetryLinkV1,
    SpanLike,
    TelemetryAttributeValue,
    TelemetryStage,
    export_telemetry_event,
)
from ._verifier_execution import (
    IsolatedVerificationRequestV1,
    IsolatedVerificationResultV1,
    IsolatedVerifierRunner,
    TrustedVerifierPolicy,
    VerifierExecutionMode,
    VerifierManifestV1,
    run_isolated_verifier,
    select_verifier_execution,
)

__all__ = [
    "ActionSemanticsV1",
    "AnchorContext",
    "AnchorHead",
    "AnchorStore",
    "AssuranceDependencyError",
    "AssuranceError",
    "AssurancePolicyError",
    "AssuranceTelemetryEventV1",
    "AssuranceTelemetryLinkV1",
    "AssuranceValidationError",
    "AssuranceVerificationError",
    "AuthorizationEnvelope",
    "CompletionSemanticsV1",
    "ClauseResultV1",
    "ClauseSeverity",
    "ClauseStatus",
    "DecisionPayloadV1",
    "Disposition",
    "Ed25519Signer",
    "EvidenceRef",
    "EvidenceTrust",
    "HistoryStatus",
    "IsolatedVerificationRequestV1",
    "IsolatedVerificationResultV1",
    "IsolatedVerifierRunner",
    "NonceRegistry",
    "NonceStatus",
    "OTEL_SEMCONV_SCHEMA_V1",
    "ProofBundleV1",
    "ProofErrorCode",
    "ProofVerification",
    "ProofVerificationContext",
    "ReceiptStatementV1",
    "ReplayContext",
    "ReplayStatus",
    "Signer",
    "SpanLike",
    "StaticKeyProvider",
    "TrustedVerifierPolicy",
    "TransportBinding",
    "TelemetryAttributeValue",
    "TelemetryStage",
    "VerificationKeyProvider",
    "VerificationSnapshotV1",
    "VerifiedEnvelope",
    "VerifierExecutionMode",
    "VerifierManifestV1",
    "WitnessStatementV1",
    "aggregate_disposition",
    "decode_profile_v1",
    "encode_profile_v1",
    "export_telemetry_event",
    "run_isolated_verifier",
    "select_verifier_execution",
    "sha256_digest",
    "sign_attestation",
    "sign_receipt",
    "sign_witness",
    "verify_attestation",
    "verify_proof_bundle",
]
