"""
veridian.observability.compliance_report
─────────────────────────────────────────
Compliance report generator for EU AI Act, NIST AI RMF, OWASP Agentic Top 10.

Generates attestation reports from proof chain data:
  - Run summary with active safety policies
  - Verifier configuration attestation
  - Model version binding for every task
  - Proof chain integrity verification
  - Incident log (verification failures, anomalies)
"""

from __future__ import annotations

import enum
import os
import tempfile
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from veridian.observability.proof_chain import ProofChain

__all__ = ["ComplianceReport", "ComplianceStandard", "ComplianceReportGenerator"]


class ComplianceStandard(enum.Enum):
    """Supported compliance standards."""

    EU_AI_ACT = "eu_ai_act"
    NIST_AI_RMF = "nist_ai_rmf"
    OWASP_AGENTIC = "owasp_agentic"


@dataclass
class ComplianceReport:
    """Generated compliance report."""

    standard: ComplianceStandard = ComplianceStandard.EU_AI_ACT
    timestamp: str = field(default_factory=lambda: datetime.now(tz=UTC).isoformat())
    total_tasks: int = 0
    chain_intact: bool = True
    model_versions: list[str] = field(default_factory=list)
    policies_active: list[str] = field(default_factory=list)
    verification_summary: dict[str, int] = field(default_factory=dict)
    incidents: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict."""
        return {
            "standard": self.standard.value,
            "timestamp": self.timestamp,
            "total_tasks": self.total_tasks,
            "chain_intact": self.chain_intact,
            "model_versions": self.model_versions,
            "policies_active": self.policies_active,
            "verification_summary": self.verification_summary,
            "incidents": self.incidents,
        }

    def to_markdown(self) -> str:
        """Generate compliance report markdown."""
        standard_names = {
            ComplianceStandard.EU_AI_ACT: "EU AI Act",
            ComplianceStandard.NIST_AI_RMF: "NIST AI RMF",
            ComplianceStandard.OWASP_AGENTIC: "OWASP Agentic Top 10",
        }
        name = standard_names.get(self.standard, self.standard.value)

        lines = [
            f"# Compliance Report — {name}",
            "",
            f"**Generated:** {self.timestamp}",
            f"**Total tasks:** {self.total_tasks}",
            f"**Proof chain intact:** {'YES — verified' if self.chain_intact else 'NO — TAMPERED'}",
            "",
            "## Model Versions",
            "",
        ]
        for mv in sorted(set(self.model_versions)):
            lines.append(f"- {mv}")
        lines.append("")

        if self.policies_active:
            lines.append("## Active Safety Policies")
            lines.append("")
            for p in sorted(set(self.policies_active)):
                lines.append(f"- {p}")
            lines.append("")

        if self.verification_summary:
            lines.append("## Verification Summary")
            lines.append("")
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            for k, v in self.verification_summary.items():
                lines.append(f"| {k} | {v} |")
            lines.append("")

        if self.incidents:
            lines.append("## Incidents")
            lines.append("")
            for inc in self.incidents:
                lines.append(f"- {inc}")
            lines.append("")
        else:
            lines.append("## Incidents")
            lines.append("")
            lines.append("No incidents recorded.")
            lines.append("")

        lines.append("---")
        lines.append("*Compliance attestation generated by Veridian v0.2.0*")
        lines.append("")
        return "\n".join(lines)

    def save(self, path: Path) -> None:
        """Atomic write: save report as markdown."""
        content = self.to_markdown()
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            "w", dir=path.parent, delete=False, suffix=".tmp"
        ) as f:
            f.write(content)
            tmp_path = Path(f.name)
        os.replace(tmp_path, path)


class ComplianceReportGenerator:
    """Generates compliance reports from proof chain data."""

    def __init__(self, proof_chain: ProofChain) -> None:
        self._chain = proof_chain

    def generate(self, standard: ComplianceStandard) -> ComplianceReport:
        """Generate a compliance report for the given standard."""
        entries = self._chain._entries
        chain_intact = self._chain.verify()

        model_versions: list[str] = []
        policies: list[str] = []
        passed_count = 0
        failed_count = 0

        for entry in entries:
            if entry.model_version:
                model_versions.append(entry.model_version)
            policies.extend(entry.policy_attestation)

            evidence = entry.verification_evidence or {}
            if evidence.get("passed"):
                passed_count += 1
            else:
                failed_count += 1

        incidents: list[str] = []
        if not chain_intact:
            incidents.append("Proof chain integrity check FAILED — possible tampering")
        if failed_count > 0:
            incidents.append(f"{failed_count} task(s) failed verification")

        return ComplianceReport(
            standard=standard,
            total_tasks=len(entries),
            chain_intact=chain_intact,
            model_versions=model_versions,
            policies_active=policies,
            verification_summary={
                "tasks_passed": passed_count,
                "tasks_failed": failed_count,
                "total": len(entries),
            },
            incidents=incidents,
        )
